version: "3.7"

services:
  backend:
    container_name: bluehat-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - ipfs-api
  redis:
      image: redis
      command: redis-server --port 6379
      container_name: redis
      hostname: redis
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
  ipfs-api:
    image: ipfs/go-ipfs
    container_name: ipfs-api
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "8080:8080"
      - "8081:8081"
      - "5001:5001"
  ngnix:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - "./ngnix/ngnix.conf:/etc/nginx/ngnix.conf"
    restart: always
    ports:
      - "80:80"
      - "443:443"